.PHONY: clean All

All:
	@echo "----------Building project:[ Week1 - Debug ]----------"
	@cd "Week1" && "$(MAKE)" -f  "Week1.mk"
clean:
	@echo "----------Cleaning project:[ Week1 - Debug ]----------"
	@cd "Week1" && "$(MAKE)" -f  "Week1.mk" clean
